### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by Beaudidly** [RIT-Space-Exploration/SPEX-Standard-Proposal#1]
Latex is a barrier to entry for some people who don't have experience with non-WYSIWYG typesetting. Most people in SPEX are primarily using windows, could you provide a guide to your workflow on how to generate PDF's and set up a quick project @runphilrun ?

**Comment by runphilrun** [comment]
@Beaudidly installation and PC setup section complete. https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/wiki

no workflow guides yet. what would be useful? a guide to the math environment? there is a ton of stuff available on the internet via google

**Comment by runphilrun** [comment]
A guide for setting up LaTeX on one's computer is found here: https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/wiki/Setting-up-your-computer-to-work-with-LaTeX

A "quickstart" guide to using LaTeX is found here: https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/wiki/LaTeX-Quickstart-Tutorial
