### ISSUE TITLE
\thanks section not displaying

### ISSUE THREAD

**Issue by jprks** [RIT-Space-Exploration/SPEX-Standard-Proposal#12]
The \thanks section for the authors is not displaying correctly in the pdf. There are no errors being thrown so it is probably getting stopped by the IEEE author formatting.

**Comment by runphilrun** [comment]
Please provide some code either here as a comment (try \`\`\`tex \<your formatted code here\> \`\`\`) or using [gist](https://gist.github.com/), otherwise I can't tell what's wrong.

As shown in [`SPEXpdd.tex`](https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/blob/master/SPEXpdd.tex), there is a long-form author block that can be used instead of `\thanks`. Try that as a workaround.

**Comment by jprks** [comment]
https://gist.github.com/jprks/d441bba4a24104d7efdbca71690f10cc

I can make that author block but the daggers won't be necessary then. Because they are not defined anymore.

**Comment by jprks** [comment]
I can do that author block but the daggers won't be necessary then. Because they are not defined anymore.

**Comment by runphilrun** [comment]
__Sidenote__: Three tick marks (\`) followed by the keyword for a code language (tex, matlab, etc) will show formatted code with syntax highlighting. Example:
```markdown
```tex
\IEEEauthorblockN{% This block is for author Names. 
    James~Emerson~Parkus\IEEEauthorrefmark{1}, %the number in the bracket is a reference number to identify this footnote. \LaTeX will figure out what symbol to put there. 
\ ```
```
replacing \ \`\`\` at the end with \`\`\` will produce:
```tex
\IEEEauthorblockN{% This block is for author Names. 
    James~Emerson~Parkus\IEEEauthorrefmark{1}, %the number in the bracket is a reference number to identify this footnote. \LaTeX will figure out what symbol to put there. 
```
So your source code would become
```tex
\IEEEauthorblockN{% This block is for author Names. 
    James~Emerson~Parkus\IEEEauthorrefmark{1}, %the number in the bracket is a reference number to identify this footnote. \LaTeX will figure out what symbol to put there. 
    David~Breen\IEEEauthorrefmark{2} 
} 
\IEEEauthorblockA{% This block is for the author Afficliations, aka department and university RIT Space Exploration, Rochester Institute of Technology 
    \\ %\\ starts a new line Rochester, N.Y. 
    \\ Email: \IEEEauthorrefmark{1}jep7631@rit.edu, \IEEEauthorrefmark{2}djb1410@rit.edu 
} 
```

**Comment by runphilrun** [comment]
The long form author block (using `\IEEEauthorblockN` and `\IEEEauthorblockA`) should not be used at the same time as the short-form (`\thanks{ }` commands). 

Have you tried commenting out the `\thanks` commands?

**Comment by jprks** [comment]
Ok thanks. I'll do that next time.

**Comment by runphilrun** [comment]
Reply here if this resolves your issue. Thanks!

**Comment by jprks** [comment]
[Cold Gas Thruster PDD.pdf](https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/files/1213184/Cold.Gas.Thruster.PDD.pdf)
Check out the first page and tell me if that is the header you want in the PDD. I commented out the \thanks section.

**Comment by runphilrun** [comment]
That header looks nice and is consistent with the [IEEE Manuscript Template for Conference Proceedings](https://www.ieee.org/conferences_events/conferences/publishing/templates.html).

Long-form author and attribution formatting should be used by default.
