### ISSUE TITLE
Add contributing guidelines

### ISSUE THREAD

**Issue by runphilrun** [RIT-Space-Exploration/SPEX-Standard-Proposal#19]
https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines

**Comment by venku122** [comment]
Ehh, These are meant for large open-source projects, where the quality of commits and code committed has to remain high. I don't see a strong need for this kind of overhead for this repo specifically. 

We already have the readme, template PDF, and wiki.

**Comment by runphilrun** [comment]
Wouldn't the quality of PDDs committed and their reviews need to remain high?

**Comment by runphilrun** [comment]
not needed
