### ISSUE TITLE
Wiki: Instructions on creating a PDD from the template

### ISSUE THREAD

**Issue by runphilrun** [RIT-Space-Exploration/SPEX-Standard-Proposal#9]
https://github.com/RIT-Space-Exploration/SPEX-Standard-Proposal/wiki/Creating-a-PDD-from-the-Template

**Comment by jprks** [comment]
I can probably help with that. Do you still need it?

**Comment by runphilrun** [comment]
We still need it. The page should describe the [ fork -> copy -> edit -> pull request ] process as used in #10

**Comment by venku122** [comment]
Covered the process via CLI. We should probably do a guide with Github Desktop as well.

**Comment by runphilrun** [comment]
Git basics tutorial belongs in a new issue. PDD creation tutorial looks good.
